---

run:
  timeout: 30m

  issue-exit-code: 1

  tests: false

  skip-dirs:
    - pkg/proto

  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - gci
    - gochecknoinits
    - gofumpt
    - goimports
    - gochecknoglobals
    - nosnakecase
    - ireturn
    - exhaustruct
    - exhaustivestruct
    - wsl

linters-settings:
  varnamelen:
    ignore-decls:
      - ip net.IP
      - c *gin.Context
      - r *http.Request
      - r *gin.Engine
      - i int
      - t time.Time
  funlen:
    lines: 100
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: camel
