---

# HTTP listen address for metadata server
listen: 169.254.169.254:80

# Whitelist source IP addresses for X-Forwarded-For header
forwardedForWhitelist:
  - 0.0.0.0/0

# Enabled sources
sources:
  - type: gpcloud
    priority: 10