---

# Debug logging enabled
debug: true

# HTTP listen address for metadata server
listen: 0.0.0.0:8080

# Whitelist source IP addresses to detect the server IP
# from the X-Forwarded-For header - useful when running behind a proxy.
forwardedForWhitelist:
  - 0.0.0.0/0

# An optional whitelist of IP addresses that are
# allowed to access the metadata server. If not set, all requests are allowed.
whitelist: []

# Enabled sources
sources: []